# Gradle VM
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

fabric.loom.multiProjectOptimisation=true

# Logging
org.slf4j.simpleLogger.

# Mod
mod_id=constructeer
mod_name=Constructeer
mod_package=xyz.lumian.constructeer

# Def
devauth=true

# Composite Defaults
do_datagen   = false
build_define = false
is_source    = false
