org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

# Mod Info
mod_id=constructeer
mod_name=Constructeer
mod_version=1.0.0
mod_package=xyz.lumian.constructeer
archives_base_name=constructeer

# Fabric & Minecraft
minecraft_version=1.21.11
loader_version=0.18.4
loom_version=1.15-SNAPSHOT
fabric_api_version=0.141.2+1.21.11
parchment_version=2025.12.20
devauth_version=1.2.2
java_version=21

# Base Dependencies
forge_config_api_port_version=21.11.1
cloth_config_version=21.11.153
build_config_version=6.0.6
