pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

dependencyResolutionManagement {
	versionCatalogs {
		create('features') {
			from(files('gradle/features.versions.toml'))
		}
	}
}

def feature_modules = [
	'core',
	'multimining',
	'toolbelt',
	'gauntlet'
]

rootProject.name = "constructeer"

includeBuild('build-logic')
include('platform-fabric')

feature_modules.each { name ->
	final def project_name = "feature-${name}"
	include(project_name)
	project(":${project_name}").name = "${rootProject.name}-${name}"
}
