pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = "constructeer"

includeBuild('build-logic')
include('feature-core')
include('feature-multimining')
include('feature-toolbelt')
include('bundle')
