plugins {
    id 'groovy-gradle-plugin'
}

repositories {
    maven {
        name = 'Fabric'
        url = 'https://maven.fabricmc.net/'
    }

    maven { url = 'https://maven.neoforged.net/releases' }

    mavenCentral()
    gradlePluginPortal()
}

static def getPlugin(provider)
{
    final def got = provider.get()
    return "${got.pluginId}:${got.pluginId}.gradle.plugin:${got.version}"
}

dependencies {
    implementation(getPlugin(libs.plugins.loom))
    implementation(getPlugin(libs.plugins.buildconfig))
    implementation(getPlugin(libs.plugins.neoforged))
}
