plugins {
    id 'constructeer.fabric-conventions'
}

fabricApi {
    configureDataGeneration {
        client = true
    }
}

dependencies {
    modImplementation libs.bundles.trinkets
    modImplementation libs.geckolib
    include(libs.geckolib)
}

buildConfig {
    forClass(project.mod_package, "CteerAutoDefine") {
        buildConfigField String.class, 'ID',         project.mod_id
        buildConfigField String.class, 'NAME',       project.mod_name
        buildConfigField String.class, 'VERSION',    features.versions.constructeer.get()
        buildConfigField String.class, 'MC_VERSION', libs.versions.minecraft.get()
        buildConfigField String.class, 'PACKAGE',    project.mod_package
    }
}
