plugins {
    id 'constructeer.mod-conventions'
}

repositories {

}

fabricApi {
    configureDataGeneration {
        client = true
    }
}

dependencies {
    modImplementation libs.trinkets
    modImplementation libs.bundles.cca
}

buildConfig {
    forClass(project.mod_package, "CteerAutoDefine") {
        buildConfigField String.class, 'ID',         project.mod_id
        buildConfigField String.class, 'NAME',       project.mod_name
        buildConfigField String.class, 'VERSION',    libs.versions.constructeer.get()
        buildConfigField String.class, 'MC_VERSION', libs.versions.minecraft.get()
        buildConfigField String.class, 'PACKAGE',    project.mod_package
    }
}
