plugins {
    id 'constructeer.neoforge-conventions'
}

static def addFeature(proj, lib)
{
    proj.dependencies {
        implementation project(path: ":${lib.get().name}")
    }
}

static def addClassTransformer(proj, String name)
{
    proj.accessTransformers {
        proj.file("src/main/resources/META-INF/${name}.cfg")
    }
}

static def nestedJar(proj, lib)
{
    proj.dependencies {
        jarJar (lib) {
            version {
                prefer lib.get().version
            }
        }
    }
}

subprojects {
    apply plugin: 'constructeer.neoforge-conventions'
}

dependencies {
    modImplementation platform.bundles.accessory

    modImplementation platform.geckolib
    nestedJar project, platform.geckolib

    features.bundles.constructeer.get().name.each { module ->
        api project(path: ":${module}")
        jarJar project(":${module}") {
            version {
                prefer '2.8.0'
            }
        }
    }
}
