[versions]
constructeer = '1.0.0'

[libraries]
core        = { module = 'xyz.lumian.constructeer:constructeer-core',        version = '1.0.0' }
multimining = { module = 'xyz.lumian.constructeer:constructeer-multimining', version = '1.0.0' }
toolbelt    = { module = 'xyz.lumian.constructeer:constructeer-toolbelt',    version = '1.0.0' }
gauntlet    = { module = 'xyz.lumian.constructeer:constructeer-gauntlet',    version = '1.0.0' }

[bundles]
constructeer = [ 'core', 'multimining', 'toolbelt', 'gauntlet' ]
