[versions]
# Mod versions
constructeer = '1.0.0'

# Dependency versions
minecraft = '1.21.11'
cca       = '7.3.0'
java      = '21'

[plugins]
loom        = { id = 'net.fabricmc.fabric-loom-remap', version = '1.15-SNAPSHOT' }
buildconfig = { id = 'com.github.gmazzo.buildconfig',  version = '6.0.6' }

[libraries]
# Shared dependencies
minecraft     = { module = 'com.mojang:minecraft',                              version.ref = 'minecraft' }
parchment     = { module = 'org.parchmentmc.data:parchment-1.21.11',            version     = '2025.12.20' }
fabric-loader = { module = 'net.fabricmc:fabric-loader',                        version     = '0.18.4' }
fabric-api    = { module = 'net.fabricmc.fabric-api:fabric-api',                version     = '0.141.2+1.21.11' }
modmenu       = { module = 'com.terraformersmc:modmenu',                        version     = '17.0.0-beta.2' }
forgeconfig   = { module = 'fuzs.forgeconfigapiport:forgeconfigapiport-fabric', version     = '21.11.1' }
clothconfig   = { module = 'me.shedaniel.cloth:cloth-config-fabric',            version     = '21.11.153' }

# Module dependencies
cca-base   = { module = 'org.ladysnake.cardinal-components-api:cardinal-components-base',   version.ref = 'cca' }
cca-entity = { module = 'org.ladysnake.cardinal-components-api:cardinal-components-entity', version.ref = 'cca' }
trinkets   = { module = 'maven.modrinth:trinkets-canary',                                   version     = '3.11.0-1.21.11' }

# Submodules
constructeer-core        = { module = 'xyz.lumian.constructeer:constructeer-core',        version.ref = 'constructeer' }
constructeer-multimining = { module = 'xyz.lumian.constructeer:constructeer-multimining', version.ref = 'constructeer' }
constructeer-toolbelt    = { module = 'xyz.lumian.constructeer:constructeer-toolbelt',    version.ref = 'constructeer' }

[bundles]
constructeer = [ 'constructeer-core', 'constructeer-multimining', 'constructeer-toolbelt' ]
cca          = [ 'cca-base', 'cca-entity' ]
