plugins {
    id 'constructeer.mod-conventions' apply false
    alias(libs.plugins.loom)
}

group   = project.mod_package
version = libs.versions.constructeer.get()

base {
    archivesName = project.mod_id
}

configurations {
    nestedJars {
        transitive = false
    }
}

dependencies {
    minecraft libs.minecraft

    mappings loom.layered() {
        officialMojangMappings()
        parchment libs.parchment
    }

    modImplementation libs.fabric.loader
    modImplementation libs.fabric.api
    modImplementation libs.modmenu

    libs.bundles.constructeer.get().name.each { module ->
        final def name = module.replace(project.mod_id, 'feature')

        api project(path: ":${name}", configuration: 'namedElements')
        nestedJars project(":${name}")
    }
}

loom.nestJars(tasks.named("jar"), configurations.nestedJars)

tasks.withType(GenerateModuleMetadata).configureEach {
    enabled = false
}

final def java_version = libs.versions.java.get().toInteger()

tasks.withType(JavaCompile).configureEach {
	it.options.release = java_version
}

java {
    sourceCompatibility = java_version
	targetCompatibility = java_version
}

processResources {
    inputs.property "version",               project.version
    inputs.property "name",                  project.mod_name
    inputs.property "minecraft_version",     libs.minecraft.get().version
    inputs.property "java_version",          java_version
    inputs.property "fabric_loader_version", ">=${libs.fabric.loader.get().version}"
    inputs.property "fabric_api_version",    "*"

    filesMatching("fabric.mod.json") {
        expand "version":               inputs.properties.version,
               "name":                  inputs.properties.name,
               "minecraft_version":     inputs.properties.minecraft_version,
               "java_version":          inputs.properties.java_version,
               "fabric_loader_version": inputs.properties.fabric_loader_version,
               "fabric_api_version":    inputs.properties.fabric_api_version
    }
}

jar {
    inputs.property "archivesName", project.base.archivesName
    from(rootProject.file("LICENSE.md"))
}
