plugins {
    id 'net.fabricmc.fabric-loom-remap'
    id 'com.github.gmazzo.buildconfig'
}

group   = project.mod_package
version = libs.versions.constructeer.get()

final def module_id   = "${project.mod_id}-${project.module_id}"
final def module_name = "${project.mod_name} ${project.module_name}"

base {
    archivesName = "${module_id}"
}

dependencies {
    minecraft libs.minecraft

    mappings loom.layered() {
        officialMojangMappings()
        parchment libs.parchment
    }

    modImplementation libs.fabric.loader
    modImplementation libs.fabric.api
    modImplementation libs.modmenu
    modImplementation(libs.clothconfig) {
		exclude(group: "net.fabricmc.fabric-api")
	}

    modApi libs.forgeconfig
}

tasks.withType(GenerateModuleMetadata).configureEach {
    enabled = false
}

final def java_version = libs.versions.java.get().toInteger()

tasks.withType(JavaCompile).configureEach {
	it.options.release = java_version
}

java {
	withSourcesJar()

    sourceCompatibility = java_version
	targetCompatibility = java_version
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "${module_id}" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

loom.runs.configureEach {
    vmArgs("-enableassertions", "-Dmixin.debug.verify=true", "-Dmixin.debug.countInjections=true")
}

processResources {
    inputs.property "version",                       project.version
    inputs.property "name",                          module_name
    inputs.property "minecraft_version",             libs.minecraft.get().version
    inputs.property "java_version",                  java_version
    inputs.property "fabric_loader_version",         ">=${libs.fabric.loader.get().version}"
    inputs.property "forge_config_api_port_version", "~${libs.forgeconfig.get().version}"
    inputs.property "fabric_api_version",            "*"

    inputs.property "mod_id",   project.mod_id
    inputs.property "mod_name", project.mod_name
    inputs.property "mod_desc", "Definitely the Minecraft mod of all time. Build fast, die young!"

    filesMatching("fabric.mod.json") {
        expand "version":                       inputs.properties.version,
               "name":                          inputs.properties.name,
               "minecraft_version":             inputs.properties.minecraft_version,
               "java_version":                  inputs.properties.java_version,
               "fabric_loader_version":         inputs.properties.fabric_loader_version,
               "forge_config_api_port_version": inputs.properties.forge_config_api_port_version,
               "fabric_api_version":            inputs.properties.fabric_api_version,

                "mod_id":   inputs.properties.mod_id,
                "mod_name": inputs.properties.mod_name,
                "mod_desc": inputs.properties.mod_desc
    }
}

if (project.do_datagen.equalsIgnoreCase('true'))
{
    fabricApi {
        configureDataGeneration {
            client          = true
            createSourceSet = true
            modId           = project.mod_id
        }
    }
}

jar {
    inputs.property "archivesName", project.base.archivesName
    from(rootProject.file("LICENSE.md"))
}

buildConfig {
    final def pkg = (project.group + '.' + project.module_id);

    forClass(pkg, "ModuleDefine") {
        buildConfigField String.class, 'ID',      project.module_id
        buildConfigField String.class, 'NAME',    project.module_name
        buildConfigField String.class, 'PACKAGE', pkg
    }
}
